Repository derechtenap/projekt-webshop, pull requests merged in 2020-08, with the labels that each got.

#17 Produktliste ajax
  data.php
  images/Avocado.jpg
  images/Bananen.jpg
  images/Gurke.jpg
  images/Paprika_bunt.jpg
  images/Zitronen.jpg
  produkte.html
  webshopdb (1).sql
Labels: backend, database, frontend

#20 Produktliste test
  card.php
  data.php
  db_login.inc.php
  images/3.jpg
  images/4.jpg
  images/5.jpg
  images/6.jpg
  images/7.jpg
  produkte.php
  warenkorb-test.html
Labels: frontend

#22 Scss patch
  .gitignore
  .vscode/settings.json
  README.md
  css/next.min.css
  css/next.min.css.map
  css/next.scss
  index.html
  js/jquery.min.js
  js/jquery.min.map
  kontakt/impressum.html
  package-lock.json
  produkte.php
  warenkorb/inhalt.html
Labels: css, frontend

#23 Prototyp einer Liste mit Modals und Cards
  card.php
  images/1.jpg
  images/2.jpg
  images/3.jpg
  images/4.jpg
  images/5.jpg
  images/6.jpg
  images/7.jpg
  package-lock.json
  produkte.php
Labels: backend, css, database, frontend, html, javascript

#29 Änderungen an der Indexseite
  css/next.min.css
  css/next.min.css.map
  css/next.scss
  images/carousel/1.jpg
  images/carousel/2.jpg
  images/carousel/3.jpg
  images/carousel/vorlage-blau.pdn
  images/carousel/vorlage-gruen.pdn
  images/carousel/vorlage-rot.pdn
  index.html
  kontakt/impressum.html
  warenkorb/inhalt.html
Labels: frontend

#32 Neue Datensätze, Verbesserung DB und PHP Variable
  card.php
  images/1.jpg
  images/10.jpg
  images/11.jpg
  images/12.jpg
  images/13.jpg
  images/14.jpg
  images/2.jpg
  images/8.jpg
  images/9.jpg
  images/default.jpg
  webshopdb.sql
Labels: backend, bug, database, frontend

#49 Fehler behoben: Cards haben jetzt immer die richtige Hintergrundfarbe
  card.php
  js/changeBackground.js
  js/kategorieFarben.js
  produkte.php
  sale.php
Labels: bug, frontend, javascript

#54 Design 2.0
  bestellUebersicht.html
  card.php
  css/_footer.scss
  css/_utils.scss
  css/next.min.css
  css/next.min.css.map
  css/next.scss
  exotisch.php
  fruechte.php
  gemuese.php
  hilfe/ueber-uns.html
  hilfe/uebersicht.html
  index.html
  js/changeBackground.js
  js/infoModal.js
  js/mwstAlert.js
  js/produkte.js
  kontakt/formular.html
  kontakt/impressum.html
  obst.php
  produkte.php
  profil/nutzer.html
  rezepte.html
  sale.php
  warenkorb/inhalt.html
Labels: frontend
